//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInformation()
        {
            this.ShoppingCarts = new HashSet<ShoppingCart>();
        }
    
        public int id { get; set; }
        public string picture { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string phoneNumber { get; set; }
        public string alternativePhoneNumber { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string otp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; }
    }
}
